version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goflare_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goflare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goflare_net

  redis:
    image: redis:7-alpine
    container_name: goflare_redis
    ports:
      - "6379:6379"
    networks:
      - goflare_net

  zookeeper:
    image: zookeeper:3.7
    container_name: goflare_zookeeper
    ports:
      - "2181:2181"
    networks:
      - goflare_net

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: goflare_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=goflare_analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper
    networks:
      - goflare_net
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.d/config.xml:ro

networks:
  goflare_net:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data:
